version: '3.7'
services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      MINIO_REGION_NAME: ${AWS_DEFAULT_REGION}
    command: 
      server /data --console-address :9001 --address :9000
    volumes:
      - ./object_storage:/data
    networks:
      - internal_network

  postgres:
    image: postgres:12.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal_network

  mlflow:
    build: .
    platform: linux
    environment:
      DB_CON_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/mlflow-db
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    ports:
      - 3000:5000
    depends_on:
      - postgres
      - minio
    networks:
      - internal_network


networks:
  internal_network:
    driver: bridge

volumes:
  db-data: